services:
  mongo:
    image: mongo:8.0.4
    container_name: mongodb
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=password
     - MONGO_INITDB_DATABASE=product-service
    ports:
      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - mongo-network
#
#volumes:
#  mongo-data:
#    driver: local
#
#networks:
#  mongo-network:
#    driver: bridge
